const Data = [
    {
        name: "Mama Mia's Pasta House",
        cuisine: "Italian",
        rating: 4.7,
        deliveryFee: 0.0,
        estimatedTime: 25,
        isTopRated: true,
        imageUrl: "https://placehold.co/400x250/dc3545/ffffff?text=Italian+Food",
    },
    {
        name: "The Curry Corner",
        cuisine: "Indian",
        rating: 4.5,
        deliveryFee: 3.5,
        estimatedTime: 40,
        isTopRated: true,
        imageUrl: "https://placehold.co/400x250/ffc107/000000?text=Indian+Curry",
    },
    {
        name: "Burger Bonanza",
        cuisine: "American",
        rating: 3.9,
        deliveryFee: 5.0,
        estimatedTime: 30,
        isTopRated: false,
        imageUrl: "https://placehold.co/400x250/20c997/000000?text=Burgers",
    },
    {
        name: "Taco Tsunami",
        cuisine: "Mexican",
        rating: 4.3,
        deliveryFee: 0.0,
        estimatedTime: 35,
        isTopRated: false,
        imageUrl: "https://placehold.co/400x250/0d6efd/ffffff?text=Tacos",
    },
    {
        name: "Sushi Zen Garden",
        cuisine: "Japanese",
        rating: 4.9,
        deliveryFee: 2.0,
        estimatedTime: 45,
        isTopRated: true,
        imageUrl: "https://placehold.co/400x250/6610f2/ffffff?text=Sushi+Rolls",
    },
    {
        name: "Vegan Vibes",
        cuisine: "Healthy",
        rating: 4.6,
        deliveryFee: 0.0,
        estimatedTime: 20,
        isTopRated: false,
        imageUrl: "https://placehold.co/400x250/fd7e14/ffffff?text=Vegan+Eats",
    },
]
export default Data;